- hosts: virtual_machines
  become: true
  tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

    - name: Add remote "ubuntu" user to "docker" group
      user:
        name: "tj"
        group: "docker"
        append: yes

- hosts: explorer
  become: true
  tasks:
    - name: Copying configs to filesystem
      copy:
        src: powerdns/
        dest: /opt/powerdns/

    - name: Starting PowerDNS
      command: docker-compose -f /opt/powerdns/docker-compose.yml up -d

- hosts: cassini
  become: true
  tasks:
    - name: Copying configs to filesystem
      copy:
        src: pihole/
        dest: /opt/pihole/

    - name: Starting Pi-Hole
      command: docker-compose -f /opt/pihole/docker-compose.yml up -d

- hosts: sputnik
  become: true
  tasks:
    - name: Copying configs to filesystem
      copy:
        src: unifi-network-application/
        dest: /opt/unifi-network-application/

    - name: Starting Unifi Network Application
      command: docker-compose -f /opt/unifi-network-application/docker-compoup se.yml -d
